Added missing templates for line tag
ezsystems/ezplatform-xmltext-fieldtype pull request #122
Opened 2021-02-15 14:19 UTC by mateuszbieniek

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/EZEE-3495
| **Type**           | Bug
| **Target version** |  `1.8`
| **BC breaks**      | no
| **Doc needed**     | no

This PR adds missing handling for the `<line>` tag.

2021-02-15 14:20 UTC, konradoboza approved these changes

2021-02-15 14:45 UTC, lserwatka commented
@mateuszbieniek could you check unit-tests here?

2021-02-15 14:45 UTC, lserwatka approved these changes

2021-02-15 14:45 UTC, alongosz reviewed
No objections to the change, but failing tests concern me a bit. They were not run in a long time AFAICS

2021-02-15 14:49 UTC, mateuszbieniek commented
@alongosz the tests fails due to some new line chars missing, for example:
```
-          <para>
-            <literallayout class="normal">This is a paragraph
+          <para><literallayout class="normal">This is a paragraph
```
but I'll give it a second look.

2021-02-16 10:06 UTC, vidarl requested changes
I would like to see some new tests that shows how that ezxmltext is now converted to docbook

I wonder if `<embed>` inside `<line>` strickly speaking should have been `<embed-inline>` on ezxmltext side? But that the legacy parser was not really strict about it...

I am keen to see how the resulting docbook looks like... it validates, right?

2021-02-17 12:33 UTC, mateuszbieniek commented
Previous change was affecting how some elements were rendered and was refactored to only affect `<line>` tags inside `<paragraph xmlns:tmp="http://ez.no/namespaces/ezpublish3/temporary/">` which were causing the issues.

2021-02-18 07:19 UTC, merged