Fixed missing 'is-linked' tag and wrong ezlink tag order
ezsystems/ezplatform-xmltext-fieldtype pull request #123
Opened 2021-02-16 15:26 UTC by mateuszbieniek

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | https://issues.ibexa.co/browse/EZP-32345
| **Type**           | Bug
| **Target version** | `1.8`

This PR fixes the issue with the conversion command which caused links to be "missing" from the RichText editor by adding the missing `is-lined` class to the `<ezembed>` and placing `<ezlink>` tag after `<ezconfig>`.

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement/fix tests
- [x] Ask for Code Review.

2021-02-16 15:37 UTC, glye approved these changes

2021-02-16 15:37 UTC, glye commented on lib/FieldType/XmlText/Converter/RichText.php
> +            $isLinked = $node->lastChild->nodeName === 'ezlink';
Comment: @mateuszbieniek found that the editor fails to read the link if the ezlink element is first. It works only if it's last. Hence this code, and the moving of the ezlink block in the xsl. It's weird, and maybe something that should be changed at some point, but not for this very urgent issue.

2021-02-16 15:38 UTC, glye commented on lib/FieldType/XmlText/Converter/RichText.php
> +            $isLinked = $node->lastChild->nodeName === 'ezlink';
Tests fail due to ezlink and ezcomment swapping places, as expected.

2021-02-16 15:44 UTC, mateuszbieniek commented on lib/FieldType/XmlText/Converter/RichText.php
> +            $isLinked = $node->lastChild->nodeName === 'ezlink';
Small addition to the explanation: `is-linked` class is required for the link indicator in the top-right corner. 
![link-indicator](https://user-images.githubusercontent.com/38975612/108085970-2e4a3880-7076-11eb-995e-24ee843964a4.png)

2021-02-16 15:46 UTC, adamwojs commented
What about CI report?

2021-02-16 15:53 UTC, mateuszbieniek commented
> What about CI report?

The tests are failing due to a change of tag order - I'll be fixing this tomorrow (hence `Implement/fix tests` is not checked out on TODO list 😉  )

2021-02-17 06:40 UTC, Steveb-p approved these changes

2021-02-17 06:40 UTC, Steveb-p commented on lib/FieldType/XmlText/Converter/RichText.php
> +            $node->setAttribute('ezxhtml:class', $class);
Personally, I'd move `$isLinked` declaration before it is used.

My reasoning for this is that we're trying to establish ("building") what `$class` the attribute should be. That's the purpose of the code in question. Suffixing class with `"is-linked"` is a special case.

```suggestion
            $class = 'ez-embed-type-image';
            
            $isLinked = $node->lastChild->nodeName === 'ezlink';
            $class .= $isLinked ? ' is-linked' : '';

            $node->setAttribute('ezxhtml:class', $class);
```

2021-02-17 07:13 UTC, konradoboza approved these changes
Apart from failing tests, +1.

2021-02-17 09:01 UTC, alongosz approved these changes

2021-02-17 12:02 UTC, vidarl requested changes
There is no test for the `is-linked` class

Looks good besides that

2021-02-17 19:30 UTC, merged

2021-02-18 09:51 UTC, glye commented
@lserwatka & others, are we ready to tag this?

2021-02-18 11:31 UTC, lserwatka commented
Yes, it was tagged @glye